version: 2

builds:
  - main: ./cmd/whport
    binary: whport
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/zhengda-lu/whport/internal/cli.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: lu-zhengda
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/zhengda-lu/whport"
    description: "Port & process manager for macOS"
    license: "MIT"
    install: |
      bin.install "whport"
    test: |
      system "#{bin}/whport", "--version"
