version: 2

builds:
  - main: ./cmd/whport
    binary: whport
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/lu-zhengda/whport/internal/cli.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - completions/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - repository:
      owner: lu-zhengda
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/lu-zhengda/whport"
    description: "Port & process manager for macOS"
    license: "MIT"
    binaries:
      - whport
    completions:
      bash: completions/whport.bash
      zsh: completions/whport.zsh
      fish: completions/whport.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whport"]
          end
